models:

  - name: dim_customers
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null
      - name: full_name
        data_tests:
          - not_null
      - name: full_name_cleaned
        data_tests:
          - not_null
          - name_seperated_w_space
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: customer_email
        data_tests:
          - not_null
      - name: customer_state
        data_tests:
          - not_null
      - name: customer_signup_date
        data_tests:
          - not_null

