sources:
  - name: faker
    database: 'project-97ea2755-962c-466f-b6c'
    schema: 'airflow_dbt_faker_ecom_raw'

    tables:
      - name: customers # alias
        identifier: raw_customers # actual table name in bq
        columns:
          - name: name
            data_tests:
              - not_null
          - name: email
            data_tests:
              - not_null
          - name: state
            data_tests:
              - not_null
          - name: customer_id
            data_tests:
              - not_null 
              - unique  
          - name: signup_date
            data_tests:
              - not_null

      - name: products
        identifier: raw_products
      - name: orders
        identifier: raw_orders