name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發
  workflow_dispatch:


env:
  GAR_LOCATION: asia-east1                    # 你的 Artifact Registry 區域
  REPOSITORY: dbt-repo                  # 你的 Artifact Registry 儲存庫名稱
  IMAGE_NAME: mydbt2                          # 你的 Docker 映像檔名稱
  JOB_NAME: mydbt2


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1. 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. 登入 GCP (使用 JSON Key)
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      # 3. 設定 Google Cloud SDK 與 Docker 認證
      - name: Set up Cloud SDK & Docker Auth
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet


      # 4. Delete all images in GAR
      - name: Delete all images and tags in GAR
        run: |
          gcloud artifacts docker images delete \
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }} \
            --delete-tags \
            --quiet


      # 5. 建置 Docker 映像檔
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
                     ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest


      # 6. 推送映像檔至 Artifact Registry
      - name: Push Docker Image to GAR
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest 


      # 7. 把 image 推到 Cloud run job
      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs update ${{ env.JOB_NAME }} \
            --image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region=${{ env.GAR_LOCATION }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}


      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery


      - name: Install dbt packages (Optional)
        run: |
          cd my_dbt_project
          dbt deps

      - name: Generate dbt Docs
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          cd my_dbt_project
          dbt docs generate


      - name: Setup Pages
        uses: actions/configure-pages@v5


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'my_dbt_project/target' # dbt docs generate 會將產物放在 target/ 目錄


      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4